# -*- coding: utf-8 -*-
"""BS - Leetocde.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOmmxxcQvXIXRQLtDBWW0pDgQuDQ3_NL
"""

#Leetcode
#Binary Search
def binarySearch(nums, target):
  l, r = 0, len(nums) - 1
  idx = -1

  while l <= r:

    mid = l + (r - l) // 2 # (r + l) // 2 - getting the mid directly as r = len(nums) - 1

    if target > nums[mid]:
      l = mid + 1

    elif target < nums[mid]:
      r = mid - 1

    else:
      idx = mid
      break

  return idx


print(binarySearch([2, 4, 6, 8, 10, 12, 14, 16], 16))
print(binarySearch([2], 2))
print(binarySearch([], 2))
print(binarySearch([2, 2, 4, 6, 8, 10, 12, 14, 16, 16], 2))

#First and Last Position using Binary Search

from typing import List

class Solution:
    def searchRange(self, nums: List[int], target: int) -> List[int]:
        first = self.binarySearch(nums, target, True)
        last = self.binarySearch(nums, target, False)
        return [first, last]

    def binarySearch(self, nums: List[int], target: int, leftSearch: bool) -> int:
        l, r = 0, len(nums) - 1
        index = -1

        while l <= r:
            mid = l + (r - l) // 2

            if target > nums[mid]:
                l = mid + 1
            elif target < nums[mid]:
                r = mid - 1
            else:
                index = mid
                if leftSearch:
                    r = mid - 1
                else:
                    l = mid + 1
        return index

BS = Solution()
print(BS.searchRange([5,7,7,8,8,10], 8))
print(BS.searchRange([5,5,10,45,19], 6))